services:
  ethereum:
    image: ethereum/client-go
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - "./ethereum:/root"
    command: >
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.api web3,eth,net,personal,miner,admin
      --dev
  ipfs:
    image: ipfs/kubo
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080:8080"
      - "5001:5001"
    volumes:
      - "./ipfs/export:/export"
      - "./ipfs/data:/data/ipfs"
