services:  
  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    ports:
      - "8545:8545"
    command: >
      ganache-cli 
      --host 0.0.0.0 
      --port 8545 
      --deterministic 
      --gasLimit 0x1fffffffffffff
    volumes:
      - ./ganache:/root/.ganache
    environment:
      - NETWORK_ID=1337

  ipfs:
    image: ipfs/kubo
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080:8080"
      - "5001:5001"
    volumes:
      - "./ipfs/export:/export"
      - "./ipfs/data:/data/ipfs"